services:
  api:
    env_file: ".env"
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      default:
        aliases:
          - api
  postgres:
    image: postgres:latest
    env_file: ".env"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      default:
        aliases:
          - postgres